allowBuilds:
  '@myriadcodelabs/uiflow': true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 0

packages:
  - '.'

onlyBuiltDependencies:
  - '@myriadcodelabs/uiflow'
  - sharp
  - unrs-resolver
  - '@tailwindcss/oxide'
